const workouts = {
    success: true,
    data: [
    {
    id: "x9RhpSemUY",
    createdAt: "2019-11-08T22:28:12.564Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191110,
    whiteboardDisplayOrder: 1,
    title: "Rest Day Overview",
    description: "*** Open 20.5 Re-Test Athletes... If you plan to re-test Open 20.4, we will have our re-test strategy posted to Monday's training day. This will be updated by mid-day Sunday, with lessons learned, and thoughts on how to approach our final go at this workout. Supple Sunday: Whether it be upon rising, before bed, or anywhere in between, working these 30 minutes will make a significant difference in our recovery, performance, and longevity.",
    resultType: 5,
    resultTypeName: "Not Scored",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 0,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [ ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "",
    hasAthletesNotes: false,
    canChangeScheduledDate: true,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "uxgRPmjFFG",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "NOic9TrNcb",
    createdAt: "2019-11-08T22:28:16.185Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191110,
    whiteboardDisplayOrder: 2,
    title: "Upper Body Mobility",
    description: "1. Puppy Pose: 1 Minute 2. Shoulder to Floor: 1 Minute 3. Wrist Stretches: 1 Minute Click 'Workout Prep Notes' for Example Videos of Each Stretch.",
    resultType: 13,
    resultTypeName: "Checkbox",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 5,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [ ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "# Upper Body ## 1. Puppy Pose: 1 Minute [Click Here](http://youtu.be/GJmSVwsnQaI) ## 2. Shoulder to Floor: 1 Minute Each Side [Click Here](http://youtu.be/D0li2U56nO4) ## 3. Wrist Stretches: 1 Minute [Click Here](http://youtu.be/-L-8YRim2nw)",
    hasAthletesNotes: true,
    canChangeScheduledDate: false,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "OX54WcKK2B",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "q7o8afuuqs",
    createdAt: "2019-11-08T22:28:19.042Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191110,
    whiteboardDisplayOrder: 3,
    title: "Lower Body Mobility",
    description: "1. Couch Stretch: 2 Minutes Each Side 2. Pigeon Pose: 2 Minutes Each Side 3. Butterfly: 90 Seconds 4. Pike: 1 Minute 5. Straddle: 1 Minute 6. Kneeling Split: 1 Minute Click 'Workout Prep Notes' for Example Videos of Each Stretch.",
    resultType: 13,
    resultTypeName: "Checkbox",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 5,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "5d8CGlTP9W"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "",
    hasAthletesNotes: false,
    canChangeScheduledDate: false,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "0Hdt0unWDj",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    }
    ]
    }

    export default workouts;