const workouts = {
    success: true,
    data: [
    {
    id: "2XHl4GlOLq",
    createdAt: "2019-10-28T11:44:15.296Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191109,
    whiteboardDisplayOrder: 1,
    title: "Recovery Day Overview",
    description: "Recovery Thursdays: Mobility to prepare for the remainder of the week. If you have access to the gym and would like to head in to mobilize further, that is ideal. But the below stretches are designed so that we can do these at home, if need be. Click 'Workout Prep Notes' for Example Videos of Each Stretch. Upper Body: 1. Puppy Pose: 1 Minute 2. Shoulder to Floor: 1 Minute 3. Wrist Stretches: 1 Minute Lower Body: 1. Couch Stretch: 2 Minutes Each Side 2. Pigeon Pose: 2 Minutes Each Side 3. Butterfly: 90 Seconds 4. Pike: 1 Minute 5. Straddle: 1 Minute 6. Kneeling Split: 1 Minute",
    resultType: 13,
    resultTypeName: "Checkbox",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 21,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "5d8CGlTP9W"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "# Upper Body ## 1. Puppy Pose: 1 Minute [Click Here](http://youtu.be/GJmSVwsnQaI) ## 2. Shoulder to Floor: 1 Minute Each Side [Click Here](http://youtu.be/D0li2U56nO4) ## 3. Wrist Stretches: 1 Minute [Click Here](http://youtu.be/-L-8YRim2nw) # Lower Body ## 1. Couch Stretch: 2 Minutes Each Side [Click Here](http://youtu.be/kbId9zYgoFQ) ## 2. Pigeon Pose: 2 Minutes Each Side [Click Here](http://youtu.be/n5M-JlU210I) ## 3. Butterfly: 90 Seconds [Click Here](http://youtu.be/mdYNs0nV5-8) ## 4. Pike: 1 Minute [Click Here](http://youtu.be/WSkPQ1lXfNk) ## 5. Straddle: 1 Minute [Click Here](http://youtu.be/HZRZ18fDleg) ## 6. Kneeling Split: 1 Minute [Click Here](http://youtu.be/0yxwdjCtM1Y)",
    hasAthletesNotes: true,
    canChangeScheduledDate: false,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "n2lVDbXHbB",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "tZnJGiwfC5",
    createdAt: "2019-10-28T11:44:16.688Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191109,
    whiteboardDisplayOrder: 2,
    title: "Thursday Pre-Game",
    description: "3 Rounds (low intensity): 1:00 Light Row 10 Dumbbell Hang Clean and Jerks (light load) 10 Glute Bridges 1:00 Light Bike 3 Walkouts 6 Wall Squats Into 3 Rounds: 4 Strict Pull-Ups 8 Kettlebell Swings (light) 12 Air Squats 24 Double-Unders 200m Jog Finish with an empty barbell, moving through the sequence twice with rest between: 5 Good Mornings 5 Pausing Back Squats 5 Elbow Rotations 5 Strict Presses 5 Stiff-Legged Deadlifts 5 Front Squats",
    resultType: 4,
    resultTypeName: "Other / Text",
    scoreCalcType: 4,
    scoreboardSortDirection: 1,
    resultsCount: 16,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "3DHp1XSoMb",
    "fQG7uhGbq8",
    "AV3ZJImwt6",
    "ggQ8RGQz8X",
    "r3CNRMSi8j",
    "k7wui7m8TE",
    "8OZDlHAExp",
    "h9vPo5JYw6",
    "QCUOoOtogo",
    "iSu93oACwo",
    "9ikRXPXECL",
    "yJIlK7TN6q",
    "Zsg2tpPwwB"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "# Thursday 'Pre-Game 3 Rounds (low intensity): 1:00 Light Row 10 Dumbbell Hang Clean and Jerks (light load) 10 Glute Bridges - [Video](http://youtu.be/M7PynZBxSR0) 1:00 Light Bike 3 Walkouts - [Video](http://youtu.be/92eVXZWgA8g) 6 Slow Wall Squats - [Video](http://youtu.be/pktIjwNiuYE) Into 3 Rounds: 4 Strict Pull-Ups 8 Kettlebell Swings (light) 12 Air Squats 24 Double-Unders 200m Jog Finish with an empty barbell, moving through the sequence twice with rest between: 5 Good Mornings 5 Pausing Back Squats 5 Elbow Rotations 5 Strict Presses 5 Stiff-Legged Deadlifts 5 Front Squats # STIMULUS * Today is an optional primer for tomorrow's Open workout. * The goal here is to get the whole body moving in a lower intensity environment.",
    hasAthletesNotes: true,
    canChangeScheduledDate: false,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "DtVQhh5bBD",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "FT2bfrceWM",
    createdAt: "2019-10-27T18:30:30.022Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191030,
    whiteboardDisplayOrder: 6,
    title: "CompTrain Mindset",
    description: "“Life is change. Growth is optional. Choose wisely.” We can all agree that the single constant in our universe is that things will change. From the most successful, to the struggling, we’ll all experience change. Yet there is something that separates the successful and the struggling. Not the type of change - because that's again just part of our world. But instead, the response to it. Change isn’t positive or negative in and of itself. It is our internal interpretation of the event that dictates whether it was good or bad. Where thoughts become actions, perception becomes reality. When we actively remind ourselves that events don't shape our world, and that our thoughts towards them do, we can see the growth opportunity in every moment. We just have to look for it.",
    resultType: 5,
    resultTypeName: "Not Scored",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 0,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "h9vPo5JYw6"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "",
    hasAthletesNotes: false,
    canChangeScheduledDate: true,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "qfFG2F4dWN",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "FNtKhHR033",
    createdAt: "2019-10-27T18:30:31.003Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191030,
    whiteboardDisplayOrder: 7,
    title: "Training Day Overview",
    description: "'Katana' Week 6: - - - - - - - - - - - - - - - - Two parts to our training day: 1. Skill conditioning, coupling the OHS barbell with a gymnastic complex. 2. Conditioning in the form of a paired down benchmark workout of ours: 'Tri Sprint Intervals V2'.",
    resultType: 5,
    resultTypeName: "Not Scored",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 0,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "hxBTjT5xIP",
    "r5pboqWEba"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "**“Katana”** **September 16 - November 11** It’s time to sharpen the blade. “Katana” is Open 2020 competition preparation. In this unique double-Open year, we first sought out a base layer of strength (Grunt Work). We then bridged the gap between it and our conditioning through routine stamina work (Sled Dog). Now, we’ll turn to peaking our abilities for the five weeks of competition ahead. We have two focus points in “Katana”: Ability Awareness Inside competition, especially in a game of inches that is the Open, awareness of our own limits is equally as important as our ability. It isn’t necessarily the sharpest sword that wins, but instead the sharpest warrior. Challenging ourselves with repetition schemes that will build both our physical capacity *and* our understanding of ourselves will prime us to give our best in the Open. We must have both dialed in. Introducing “Capacity Builders”, we’ll routinely approach larger sets of Open-like movements and repetition schemes. Fine tuning familiar movements with unfamiliar conditions, our aim here is to prepare for any challenge we may see in October. During the Open, upon each Thursday evening announcement, the CompTrain team will be creating our full strategy overnight for the following day’s attempt. Saturday becomes our practice and preparation day, debriefing Friday and planning for re-attack on Monday. Whatever comes in October, we’ll be ready.",
    hasAthletesNotes: true,
    canChangeScheduledDate: true,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "eScvyxnTSZ",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "TGNc19SS2p",
    createdAt: "2019-10-27T18:30:31.699Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191030,
    whiteboardDisplayOrder: 8,
    title: "Mobility and Activation",
    description: "Click 'Workout Prep Notes' Below",
    resultType: 5,
    resultTypeName: "Not Scored",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 0,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [ ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "# MOBILITY ## Pigeon Stretch: 2-3 Minutes Each Side [Video](http://youtu.be/n5M-JlU210I) ## Ankle Dorsiflexion: 1-2 Minutes [Video](http://youtu.be/O9u1_Bvpng4) ## Barbell Thoracic Opener: 2-3 Minutes [Video](http://youtu.be/4_DUZpPAhVc) # ACTIVATION ## EMOM 9: Minute 1: 1 Minute Easy Machine Minute 2: 1 Minute Inchworms [Video](http://youtu.be/gDweumAbvfQ) Minute 3: 30 Seconds Front Plank + 30 Seconds of Sit-ups ## Barbell Warmup 5 Good Mornings 5 Back Squats 5 Elbow Rotations 5 Strict Press & Reach 5 Romanian Deadlifts 5 Front Squats [Video](http://youtu.be/mIjiebAcBJc) *For specific movement prep for each workout, see corresponding “Workout Prep Notes”",
    hasAthletesNotes: true,
    canChangeScheduledDate: true,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "W0YjKlAL30",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "g5pSmZ3grx",
    createdAt: "2019-10-27T18:30:32.139Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191030,
    whiteboardDisplayOrder: 9,
    title: "Gymnastic Conditioning",
    description: "On the 2:00 x 5 Sets: 9 Overhead Squats (115/85) 6 CTB Pull-Ups 1-3 Bar Muscle-Ups Take OHS barbell from the floor.",
    resultType: 0,
    resultTypeName: "Time",
    scoreCalcType: 1,
    scoreboardSortDirection: 1,
    resultsCount: 77,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "V8IKIUyIbF",
    "XavuhsO1R0",
    "iSu93oACwo"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "# 'Gymnastic Conditioning' On the 2:00 x 5 Sets: 9 Overhead Squats (115/85) 6 CTB Pull-Ups 1-3 Bar Muscle-Ups ***Kilos: 52/38*** # STIMULUS * Barbell cycling and gymnastics. Fine tuning this combination. * A moderate load on the OHS, where we can cycle through without a pause for all five rounds. * Aim is to move directly into the gymnastic complex to follow. * Naturally, OHS take a toll on our pulling/grip strength, resulting in a effective training combination. * Record all five completion times. # SUBSTITUTIONS ## Bar MU * Reduce volume (2 or 1 per round) * CTB throughout all rounds - 9 reps, 7 reps, 5 reps.",
    hasAthletesNotes: true,
    canChangeScheduledDate: false,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "6q3varc7xW",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "F3NZW6GAmJ",
    createdAt: "2019-10-27T18:30:32.694Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191030,
    whiteboardDisplayOrder: 10,
    title: "'Tri Sprint Intervals V2'",
    description: "3 Rounds: AMRAP 4: 30 Shuttle Runs (10 Meters) 20/15 Calorie Assault Bike Max Calorie Row Rest 4 Minutes Between Rounds",
    resultType: 7,
    resultTypeName: "Calories",
    scoreCalcType: 2,
    scoreboardSortDirection: 0,
    resultsCount: 79,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "3DHp1XSoMb",
    "9ikRXPXECL",
    "yJIlK7TN6q",
    "FvelGsOivV"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "# 'Tri Sprint Intervals V2' 3 Rounds: AMRAP 4: 30 Shuttle Runs (10 Meters) 20/15 Calorie Assault Bike Max Calorie Row Rest 4 Minutes Between Rounds # STIMULUS * A modified version of the original V2 workout (5 rounds originally, completing 3 today). * Reducing volume so that we are fine tuning our engine, but not overdoing it for Friday. * Let's push our intensity, but focus on consistency across the three rounds. # SUBSTITUTIONS ## Shuttle Runs * 20 Burpees per round ## Assault Bike 30/20 Schwinn Bike 20/15 Calorie Erg Bike # MOVEMENT PREP ## Warmup Set Steadily ramp up our intensity over 2 rounds: 6 Shuttle Rungs 8 Calorie Assault Bike 10 Calorie Row Rest as needed between, and on the second round, the aim is to build to our planned workout intensity on each movement.",
    hasAthletesNotes: true,
    canChangeScheduledDate: false,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "aTjmqvNDko",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "mr9UC2KW1R",
    createdAt: "2019-10-27T18:30:25.665Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191029,
    whiteboardDisplayOrder: 7,
    title: "CompTrain Mindset",
    description: "“Trade your expectation for appreciation, and the world changes around you” - Tony Robbins There will be a final cup of morning coffee for us. There will be the last chance for us to listen to the radio. And if we are lucky enough to have kids, there will be a last time we get to sit in traffic as we drive them to school. As Tony Robbins quotes, if we can remove expectations from the norm, and replace them with a sense of gratitude, our entire world changes. We start to see the abundance in life again, versus it being blended into the background.",
    resultType: 5,
    resultTypeName: "Not Scored",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 0,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "V8IKIUyIbF"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "",
    hasAthletesNotes: false,
    canChangeScheduledDate: true,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "qfFG2F4dWN",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "tdtmgeG9td",
    createdAt: "2019-10-27T18:30:26.195Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191029,
    whiteboardDisplayOrder: 8,
    title: "Training Day Overview",
    description: "'Katana' Week 6: - - - - - - - - - - - - - - - - Three parts to our Tuesday 1. Push Jerk 2. Conditioning 3. Recovery Bike",
    resultType: 5,
    resultTypeName: "Not Scored",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 0,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "V8IKIUyIbF",
    "FrQGIrNfi8",
    "VkmcRrRQFN",
    "O8xUgMBLOp"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "**“Katana”** **September 16 - November 11** It’s time to sharpen the blade. “Katana” is Open 2020 competition preparation. In this unique double-Open year, we first sought out a base layer of strength (Grunt Work). We then bridged the gap between it and our conditioning through routine stamina work (Sled Dog). Now, we’ll turn to peaking our abilities for the five weeks of competition ahead. We have two focus points in “Katana”: Ability Awareness Inside competition, especially in a game of inches that is the Open, awareness of our own limits is equally as important as our ability. It isn’t necessarily the sharpest sword that wins, but instead the sharpest warrior. Challenging ourselves with repetition schemes that will build both our physical capacity *and* our understanding of ourselves will prime us to give our best in the Open. We must have both dialed in. Introducing “Capacity Builders”, we’ll routinely approach larger sets of Open-like movements and repetition schemes. Fine tuning familiar movements with unfamiliar conditions, our aim here is to prepare for any challenge we may see in October. During the Open, upon each Thursday evening announcement, the CompTrain team will be creating our full strategy overnight for the following day’s attempt. Saturday becomes our practice and preparation day, debriefing Friday and planning for re-attack on Monday. Whatever comes in October, we’ll be ready.",
    hasAthletesNotes: true,
    canChangeScheduledDate: true,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "eScvyxnTSZ",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "eQI9dVhsQy",
    createdAt: "2019-10-27T18:30:27.120Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191029,
    whiteboardDisplayOrder: 9,
    title: "Mobility and Activation",
    description: "Click 'Workout Prep Notes' Below",
    resultType: 5,
    resultTypeName: "Not Scored",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 0,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [ ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "# MOBILITY ## Banded Hamstring Distraction: 1-2 Minutes Each Side [Video](http://youtu.be/_jVJpxBNqlY) ## Pike Stretch: 2 Minutes [Video](http://youtu.be/WSkPQ1lXfNk) ## Lacrosse Ball Hamstring Stretch: 2 Minutes Each Side [Video](http://youtu.be/ybyiNvby2v8) # ACTIVATION ## 4-5 Rounds: 30 Single Unders 15 AbMat Sit-ups 5 Walkouts [Video](http://youtu.be/92eVXZWgA8g) ## Barbell Warmup 5 Good Mornings 5 Back Squats 5 Elbow Rotations 5 Strict Press & Reach 5 Romanian Deadlifts 5 Front Squats [Video](http://youtu.be/mIjiebAcBJc) *For specific movement prep for each workout, see corresponding “Workout Prep Notes”",
    hasAthletesNotes: true,
    canChangeScheduledDate: true,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "W0YjKlAL30",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "bYytSYNUqn",
    createdAt: "2019-10-27T18:30:27.652Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191029,
    whiteboardDisplayOrder: 10,
    title: "Push Jerk",
    description: "On the 2:00 x 5 Sets: 3 Push Jerks Barbell taken from the rack. Aim is to build to a moderate load, but not a heavy. Set #1 - 60% of estimated 1RM Set #2 - 65% Sets #3+4+5 - 70-75%",
    resultType: 3,
    resultTypeName: "Load",
    scoreCalcType: 1,
    scoreboardSortDirection: 0,
    resultsCount: 126,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "UIXa0O9TJ1"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "",
    hasAthletesNotes: false,
    canChangeScheduledDate: false,
    isBenchmark: false,
    libraryId: null,
    libraryType: 0,
    isBarbellLift: true,
    bblId: "ppRTGVRwK2",
    sourceScheduledWorkoutId: null,
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "9AWS2CDLrA",
    createdAt: "2019-10-27T18:30:28.423Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191029,
    whiteboardDisplayOrder: 11,
    title: "'Bruiser'",
    description: "AMRAP 12: 15 Push Jerks (115/85) 30 Air Squats 60 Double Unders",
    resultType: 1,
    resultTypeName: "Rounds + Reps",
    scoreCalcType: 1,
    scoreboardSortDirection: 0,
    resultsCount: 124,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "Q45eeXwOvG",
    "h9vPo5JYw6",
    "9iI9OsXVAX",
    "UIXa0O9TJ1"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "# 'Bruiser' AMRAP 12: 15 Push Jerks (115/85) 30 Air Squats 60 Double Unders ***Kilos: 52/38*** # STIMULUS * A moderate push jerk for reps is the focus of this effort. * DU and Air Squats purely to challenge the movement. * Aim is for a moderate load that we could cycle for 20-25+ reps unbroken when fresh. # STRATEGY * With a relatively 'shoulderly' combination (DU + PJ), pacing our upper body will be of importance. * Break up the PJ before we need to. Example break up strategies can be 8-7, or 6-5-4. * Be diligent with our breaks *between* sets on the PJ. This is where time disappears. * Lock in a steady pace on the air squats. This is where we breathe best. * Consistent chunks on the DU's. Much like the PJ, let's break these before we need to. 30-30, 20-20-20 being options. Naturally ideal to go unbroken here, but with a 12:00 time cap, let's see the larger effort for what it is. # SUBSTITUTIONS ## Double-Unders * 15/12 Calorie Ski Erg * 15/12 Calorie Row * 12/9 Calorie Assault Bike # MOVEMENT PREP ## Warmup Set 2 Rounds, with the first being at a weight lighter than our working load. Following, build to our loading and repeat for a second iteration. 5 Push Jerks 15 Air Squats 20 Double-Unders",
    hasAthletesNotes: true,
    canChangeScheduledDate: false,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "0NYC0ry8bZ",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "jNy9qbtAl6",
    createdAt: "2019-10-27T18:30:29.687Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191029,
    whiteboardDisplayOrder: 12,
    title: "Recovery Bike",
    description: "3 Rounds: 3:00 Recovery Bike* Between sets, 20 GHD Sit-Ups. In every 3:00 interval, the aim is to gradually increase our speed. Minute 1 - Light Pace Minute 2 - Moderate Pace Minute 3 - Moderate/Fast Pace In the entire duration, we are holding a recovery pace, but we are moving from 'conversational' to a relatively challenging pace in the final minute. No rest between rounds - we'll get right back on the bike.",
    resultType: 13,
    resultTypeName: "Checkbox",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 76,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "3DHp1XSoMb",
    "rk5ieibGyP",
    "Y8GAfTQjlS",
    "sZOLntZRGl"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "",
    hasAthletesNotes: false,
    canChangeScheduledDate: false,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "zk4P4RxM40",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "4nvPs5OO2b",
    createdAt: "2019-10-27T18:30:20.053Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191028,
    whiteboardDisplayOrder: 6,
    title: "CompTrain Mindset",
    description: "“Our greatest fear in life should not be failure. Our greatest fear in life should be succeeding in things that don’t matter.” – Francis Chan One of life’s greatest tragedies: we tend to think that things will be different if we achieve more, win more, or make more money. But if those things have never changed us before, even if we win the world… would it change us today? Like thirsty people guzzling salt water, it’s a never-ending cycle that does not lead to fulfillment. Yet we can work tirelessly for that next finish line, putting all of eggs in that basket, wishing, hoping, and working tirelessly to get there. One of our greatest fears, as written in the quote above, is to get there, and to realize… we didn’t climb the right ladder. It didn’t bring us to where we wanted to be. How we wanted to feel. It always boils down to this – the quality of our relationships, the positive influence we impart on others, and who we become in the process. Hustle is crucial, but placing first things first is absolutely vital. Which ladder are we climbing today?",
    resultType: 5,
    resultTypeName: "Not Scored",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 0,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "h9vPo5JYw6",
    "Hcl7kgiTPB",
    "vpJqkEzaNO"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "",
    hasAthletesNotes: false,
    canChangeScheduledDate: true,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "qfFG2F4dWN",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "jeycXCMDwB",
    createdAt: "2019-10-27T18:30:21.231Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191028,
    whiteboardDisplayOrder: 7,
    title: "Training Day Overview",
    description: "'Katana' Week 6: - - - - - - - - - - - - - - - - Open 20.3 Re-Test Day. Re-Test strategy, with lessons learned over the weekend, below.",
    resultType: 5,
    resultTypeName: "Not Scored",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 0,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "9ikRXPXECL",
    "bxoFHTtvld",
    "Hcl7kgiTPB"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "**“Katana”** **September 16 - November 11** It’s time to sharpen the blade. “Katana” is Open 2020 competition preparation. In this unique double-Open year, we first sought out a base layer of strength (Grunt Work). We then bridged the gap between it and our conditioning through routine stamina work (Sled Dog). Now, we’ll turn to peaking our abilities for the five weeks of competition ahead. We have two focus points in “Katana”: Ability Awareness Inside competition, especially in a game of inches that is the Open, awareness of our own limits is equally as important as our ability. It isn’t necessarily the sharpest sword that wins, but instead the sharpest warrior. Challenging ourselves with repetition schemes that will build both our physical capacity *and* our understanding of ourselves will prime us to give our best in the Open. We must have both dialed in. Introducing “Capacity Builders”, we’ll routinely approach larger sets of Open-like movements and repetition schemes. Fine tuning familiar movements with unfamiliar conditions, our aim here is to prepare for any challenge we may see in October. During the Open, upon each Thursday evening announcement, the CompTrain team will be creating our full strategy overnight for the following day’s attempt. Saturday becomes our practice and preparation day, debriefing Friday and planning for re-attack on Monday. Whatever comes in October, we’ll be ready.",
    hasAthletesNotes: true,
    canChangeScheduledDate: true,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "eScvyxnTSZ",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "NTN8IeGPAf",
    createdAt: "2019-10-27T18:30:23.637Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191028,
    whiteboardDisplayOrder: 8,
    title: "Re-Test Strategy",
    description: "Click 'Workout Prep Notes'",
    resultType: 5,
    resultTypeName: "Not Scored",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 0,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [ ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "## Open 20.3 Re-Test Strategy In what may be the shortest workout in the Open this year, every rep/second brings significant change. As we enter tomorrow's re-attempt, it's not a flipping of a strategy we are going for. It's one or two minor adjustments to lead to that relatively small, but impactful score change. Below are some overarching themes from the first attempts. **Bucket 1 Athletes (finishing the workout)** Two points to cover: 1. Strict HSPU. 2. The second bar is 'the workout'. For us, 'Diane' is our buy-in. But for many of us, the HSPU standard proved to be a difficult task. What is not a far-fetched thought, is to complete some (or many), as strict handstand pushups. When we complete this motion strict, the standard is far easier to find. If we were missing reps, or forced to hold awkward pauses at the top of each rep on Friday, this can be a consideration given it's speed and consistency. Naturally, this is not a wise plan for those who would run into a wall on our overhead strength if we start as strict. It's more of a way to think through a means to clear the standard with minimal extra thought required. In either situation, kipping or strict, we still see 'Diane' as the buy-in to the workout, which is the second barbell. The second barbell, for all intents and purposes, is the workout. If we were to 'assign' rough effort percentages to all four stations in 20.3... this 315/205 barbell gets 80% With our recent experience from Friday, we likely have a slightly adjusted game plan to attacking these 45 reps. But with that, when in doubt, *small sets usually is the default go to*. That is, if we are considering 8-7-6 in the 21's but are even a little bit 'iffy' about it, thinking about our transitions between sets, let's go 6-5-5-5. Get our reps, and get the bar off our body. Take our quick break, and then right back on it. What we want to avoid is the *large breaks*. That's where our time disappears. **Bucket 2 Athletes (time capped in the second half)** Two points to cover: 1. Refined HSPU strategy. 2. Refined Barbell #2 strategy. For us, 'Diane' proved to be a challenging, but manageable buy-in. When we got to the 315/205 barbell however, it was like a freight truck just hit us. With the recent effort in mind, we likely have some minor, yet impactful, adjustments to our rep schemes. On the handstand pushups inside 'Diane', let's think through our breakup strategy. The first goal is to meet the standard with ease. It is not worth the risk of running close to no-reps here. We'd rather slow things down a bit, and nail every rep. The risk is not worth the reward here. We likely came out with an appropriate deadlift breakup strategy, but... if we felt that second barbell was that much heavier, we can consider breaking up this first barbell even more so. When you think about it, a reset on a deadlift barbell is *fast*. Kicking up to a handstand, is not. So on the movement where we can reset within only a handful of seconds, it's worth breaking *a little more than we need to* knowing that 315/205 bar lay ahead. We also have a better thought process now on how to approach that second bar. Thinking through the time we had, and the reps we moved through, small adjustments here can make all the difference. Some athletes went straight to steady singles from the onset, and may have ended around 15/16 reps in 2:30 remaining work time (purely as an example). That same athlete may very well find 21 by considering a set strategy. 7x3, 5-4-3-3-3-3, etc. Harnessing the touch and go elastic response is a powerful advantage. The challenge is naturally 'how many'. Now with the experience of the workout beneath our belt, we have the insight on what change that may be. **Bucket 3 Athletes (working on finishing Diane, and getting to the 315/205 barbell)** Two points to cover: 1. Marking hands for HSPU 2. HSPU breakup strategy For us, this is a handstand pushup workout. And we likely found a sticky spot in the workout where we struggled on the HSPU. Whether it be the shear volume, or positioning, something slowed us down. In our warmup tomorrow, let's be diligent in marking where we place our hands. We likely found something to improve from Friday's attempt, and a little bit of practice here with finding that ideal setup with our hands goes a long way. Proper hand/head position in the bottom is absolutely critical for a powerful kip, so let's give due diligence towards finding these positions. We also likely have an idea of what to change for our HSPU strategy. When we hit a wall in this movement, we often.. hit a wall. Reps slow dramatically. Although this may happen *regardless* in this workout, the aim is to dance along that threshold line. If we felt that 5's to start was too aggressive, and we slowed our pace after 3-4 sets or in the 15's, let's start with 3's. If we started with 3's, and that slowed, start with 2's. But a small change here, that leads to a single more rep, is highly impactful. There will be potentially hundreds, if not thousands, of ties inside this workout. A single more rep goes a long way.",
    hasAthletesNotes: true,
    canChangeScheduledDate: true,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "SZAEDfCfzR",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "UoY7gAVA5q",
    createdAt: "2019-10-27T18:30:23.717Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191028,
    whiteboardDisplayOrder: 9,
    title: "Mobility and Activation",
    description: "Click 'Workout Prep Notes' Below.",
    resultType: 5,
    resultTypeName: "Not Scored",
    scoreCalcType: -1,
    scoreboardSortDirection: -1,
    resultsCount: 0,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [ ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "# MOBILITY ## Banded Hamstring Distraction: 1-2 Minutes Each Side [Video](http://youtu.be/_jVJpxBNqlY) ## Pike Stretch: 2 Minutes [Video](http://youtu.be/WSkPQ1lXfNk) ## Lacrosse Ball Hamstring Stretch: 2 Minutes Each Side [Video](http://youtu.be/ybyiNvby2v8) # ACTIVATION 3 Rounds, at very low intensity: 1:00 Light Row 3 Walkouts 5 Empty Bar Good Mornings 5 Empty Bar Stiff-Legged Deadlifts 12 AbMat Sit-Ups Load a light load onto the barbell (about half of the working load of your “Diane” weight). At low intensity, 1 round: 3 Deadlifts, :10s HS Hold 3 Deadlifts, 1 Wall Walk 3 Deadlifts, 2-3 Strict Handstand Pushups",
    hasAthletesNotes: true,
    canChangeScheduledDate: true,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "W0YjKlAL30",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    },
    {
    id: "tIASe6MTIa",
    createdAt: "2019-10-27T18:30:24.842Z",
    affId: null,
    schedulerId: null,
    workoutSourceType: null,
    track: "Masters 35-39: Open",
    trackId: "n6AZZJTWZx",
    scheduledDateInteger: 20191028,
    whiteboardDisplayOrder: 10,
    title: "Open 20.3",
    description: "21 Deadlifts, 21 Handstand Pushups 15 Deadlifts, 15 Handstand Pushups 9 Deadlifts, 9 Handstand Pushups Pounds – 225/155 Kilos – 102.5/70 Directly into… 21 Deadlifts, 50′ Handstand Walk 15 Deadlifts, 50′ Handstand Walk 9 Deadlifts, 50′ Handstand Walk Pounds – 315/205 Kilos – 143/93 9:00 Time Cap.",
    resultType: 0,
    resultTypeName: "Time",
    scoreCalcType: 0,
    scoreboardSortDirection: 1,
    resultsCount: 65,
    fistbumpsCount: 0,
    commentsCount: 0,
    movementIds: [
    "r3CNRMSi8j",
    "aPz3tX2Uwh",
    "9iu4RgWSgi"
    ],
    coachesNotes: "",
    hasCoachesNotes: false,
    athletesNotes: "# OPEN 20.3 21 Deadlifts, 21 Handstand Pushups 15 Deadlifts, 15 Handstand Pushups 9 Deadlifts, 9 Handstand Pushups *Pounds – 225/155 Kilos – 102.5/70* Directly into… 21 Deadlifts, 50′ Handstand Walk 15 Deadlifts, 50′ Handstand Walk 9 Deadlifts, 50′ Handstand Walk *Pounds – 315/205 Kilos – 143/93* With a 9:00 Time Cap: **Initial Strategy Video Posted - [Click Here](https://m.youtube.com/watch?feature=youtu.be&v=yUd9aF6Ukog)** # INITIAL THOUGHTS A repeat workout, Open 18.4. Across our ability levels, this workout can vary significantly in how it looks and feels. For some, this is a sprint from the onset. For others, it's a steady-and-heavy grind on the barbell. But in all situations, we have three initial takeaways that can apply to all. Takeaway #1 - Breakup the Deads Early * Pacing the deadlifts applies to all. The opening sets are truly our 'buy-in' reps. Even Games level athletes are breaking up the opening barbell weight several times. Takeaway #2 - Touch and Go Deadlifts * The 'stretch reflex' that takes place in a touch-and-go deadlift is a massive advantage. When cycling a deadlift barbell for higher reps such as in this workout, this can amount to a massive advantage if we use it. Commonly in workouts, 'fast singles' are a great option. We actually want to get away from that here, and instead move with 'fast sets'. Let's break up the reps early, as in the first takeaway point above, but let's break it up into *sets.* Takeaway #3 - Dial in HSPU Standard * Fine tune our ability to meet the standard in our warmup. Points below to help us meet the requirement, and diligence towards these will minimize no-reps. From marking the hands on the floor, to changing a hand position slightly, these small adjustments can make all the difference. # STRATEGY In our initial strategy video, we broke things down into (3) buckets, purely for starting points. As we look at the workout, whether we completed this in 2018 or not, let's take an honest, educated guess on where we might finish 'Diane'. **Bucket #1** * Finish 'Diane' in ~2:30 * Finish entire workout ~Sub 7:00 Our Games level group will come down to the 15's and the 9's of the heavier deadlift barbell. When you think about it, breaks between these sets *are the only moments* in the entire workout where athlete's at this level are resting. The opening weight deadlifts are not the separator, and neither are the transitions to or from the HSPU/HSW. It becomes a test of how well can we push that heavy barbell. But by 'push' this doesn't mean unbroken, nor does it even mean big sets. Example breakup strategy below for a Games level athlete who completed this workout in the 6:30 range: First *and* Second Barbell 21's - 6-5-5-5 15's - 6-5-4 9's - 5-4 Breaks between sets on the first barbell was a matter of 2-3 seconds. Just enough to break the 'time under tension', and we got right back on it. On the second barbell, it was a little more stretched out, and rightfully so. More now towards 5 seconds. The take home point here is that consistent movement forward with touch and go sets is the key here, with 'the workout' being the final two sets at that heavy barbell. On the handstand walks, all athletes in this group are doing the 50' distance unbroken. Our *speed* of the walk does indeed matter here however. With 150' for time, it's not uncommon to see 15+ second differences, *even with* unbroken efforts. As we enter these handstands, remind ourselves to fall forward, pushing our speed knowing that it's a short 25' distance each way. The less time we're on our hands, the better. **Bucket #2** * Finish 'Diane' in ~4:00 * Goal is to get as far as we can in the second 21-15-9 (and to maybe even finish). This group has a 'Diane' time somewhere in the 3:30-5:30 range. For the effort today, we are *pacing* our 'Diane' to the tune of about 45s-1:00 slower than what we would if it were solo. What this looks like, is frequent breaks on the deadlits, and consistent chunks on the HSPU. Beyond this first 21-15-9, the big separator is the heavy barbell. This is where we can see 1:00+ separate athletes in the completion of just that first set of 21. Knowing our ability level, and how much time is left on the clock, it's our aim to *space out our effort over the time remaining*. If we have 5:00, breaking up the deadlifts into small chunks (let's go with 7x3 as an example) can be a smart start knowing that we may have a chance to attempt *45* reps at this weight. If we have 2:00 left, we know it's now time to push. It's going to be on the only time we're on that barbell, and our aim there may be to make it to one length of the handstand walk. On these handstand walks, where we naturally have many different ability levels, let's draw back to two focus points: - Composure. Don't rush the kick up. This is where we often have to come right back down, as we weren't patient enough to take a breath beforehand, as well as, allow the feet to travel up and *over our head* before we take our first step. Better to take a brief moment here and *nail* the attempt, than to waste precious seconds (and energy) with failed attempts. - Grip the Ground. A quick cue to dig our *fingers* into the ground. Especially when we get metabolic and out of breath, we can lose some fundamentals. Grip the ground with your fingers to better support our handstand. **Bucket #3** * Aiming to finish 'Diane' * AMRAP Deadlifts in time remaining. This group is focused on the handstand pushups. This is our battle to fight today, and can separate us by *minutes* when we strategize properly. On the deadlifts of this first part, we are pacing just like the above two groups: conservative. Whether it's 6-5-5-5, 7x3, or a combination of the two, we like touch-and-go reps for the reasons specified above, and we like the early breakups as this is not our biggest battle to fight in this workout. On the handstand pushups, after spending ample time in our warmup fine-tuning the standard, it's our aim to first minimize all no reps due to positioning. If there is a chance we are going to receive a no-rep because of our posture on the wall, rep strategy doesn't really matter. We're going to have to adjust dramatically regardless. So our first aim is to truly game plan around, 'how can I best minimize no reps?'. Following that, we then think through rough breakup strategies. Below, purely for example: 21's - 5-5-4-4-3 15's - 5x3 9's - 3x3 This would be controlled breaks between, using either the clock, our our judge, to hustle us back on the wall. On the handstand pushups, *loading* can be a large benefit here. What that is referring to is the power of our kip. We essentially have two 'styles' of kipping handstand pushups: the 'frog kick', and the 'ball up'. In the frog kick, it's a quick bend at the knees, and a flick to extension. It's a tight and fast kip. But... it doesn't bring a ton of power behind it. For athletes who are strong on the HSPU, a great option for speed. But if we know we are going to struggle in the later portions of this opening 21-15-9, the 'ball up' technique can leverage more *hip power* into our kip. The ball up technique starts by coming to dead-stop headstand (note that for the workout, each rep *must* start from a handstand, or full lockout with heels above the tape line). From here, as we are resting in our tripod (head, hand, hand). we're going to bring our legs to our chest. We're going to ball up, with our knees coming below our waist. When this kick opens up, in comparison to the 'frog' style, there's far more power. The downside, is that it's simply a bit slower. But based on where we are with our handstand pushups, a very smart strategy to use for longevity in this workout. # OPEN 20.3 PRIMER Build to a moderate load (about 3/4 of the working load of your “Diane”). At low intensity, 2 rounds: 3 Deadlifts, 3 Kipping Handstand Pushups Build steadily to the working load of the second deadlift barbell. As we build, practice handstand walking 10-20′ between builds. After building, complete one round, at low intensity: 2-3 Deadlifts, 10-20′ Handstand Walk (or 2-3 practice attempts) We are allowed to have two barbells for the workout, where at this time we can setup our “Diane” starting weight. Final dry-run round: 2 Rounds: 3 Deadlifts (Bar 1) + 3 Handstand Pushups Directly into… 1 Round: 2 Deadlifts (Bar 2) + 10-20′ Handstand Walk (or 2-3 practice attempts)",
    hasAthletesNotes: true,
    canChangeScheduledDate: false,
    isBenchmark: false,
    libraryId: null,
    libraryType: null,
    isBarbellLift: false,
    bblId: null,
    sourceScheduledWorkoutId: "kjWhfLjrQn",
    publishingScheduledWorkoutId: null,
    workoutPublisherId: null
    }
    ]
    }

    export default workouts;